# WEEK3 HOMEWORK1
# Lesson: List, tuples, sets

# Task1: get the largest number from a list of 10 rand nums
# Challenge: use the while loop and the random module to generate numbers

"""
Action plan:
* generate empty list
* append list with random int generated by rand module
* increment the while loop
* use the max method to extract the largest value
"""

# import the random module
import random as rd

# Declare empty list
number_list = []

# Declare empty integer
random_number = int()

# Declare null iterator
iterator = 0

# Create the while loop
while iterator <= 10:
  random_number = rd.randint(-1000, 1000) 
  number_list.append(random_number)
  iterator += 1

# Print the list
print(f"The list of numbers is:")
print(number_list)
print(f"The maximum value in the list is {max(number_list)}.")

